-- 코드를 입력하세요
-- FIRST_HALF
-- SHIPMENT_ID	FLAVOR	TOTAL_ORDER

-- ICECREAM_INFO
-- FLAVOR	INGREDIENT_TYPE
SELECT f.FLAVOR
FROM ICECREAM_INFO i
inner join FIRST_HALF f on (i.FLAVOR = f.FLAVOR)
WHERE TOTAL_ORDER > 3000
and INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC
;