-- 코드를 입력하세요
-- FACTORY_ID, FACTORY_NAME, ADDRESS, TLNO
-- 공장 ID,     공장 이름,           주소,      전화번호
SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
FROM FOOD_FACTORY
WHERE ADDRESS like '강원도%'
ORDER BY FACTORY_ID
;